# Generated by Django 5.1.3 on 2024-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('History', 'History'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Biography', 'Biography'), ('Poetry', 'Poetry'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Thriller', 'Thriller'), ('Children', 'Children'), ('Art', 'Art'), ('Drama', 'Drama'), ('Comic', 'Comic'), ('Classic', 'Classic'), ('Cooking', 'Cooking'), ('Self-Help', 'Self-Help'), ('Philosophy', 'Philosophy'), ('Religion', 'Religion')], max_length=100),
        ),
    ]
